defaults:
  - _base
  - _self_

name: 'MLP'

ortho_init: False

# mlp stractor
shared_net:
    dims: [64,64]
    acts: ['relu','relu']
policy_net:
    dims: [64]
    acts: ['tanh']
value_net:
    dims: [64]
    acts: ['tanh']
