defaults:
  - _synthetic_env_base
  - _self_
name: OddOneOutN4C2S2S1
dataset_checkpoint:
    entity: ''
    project: ''
    run_id: ''
    file: 'OddOneOutEnv-N4-4C2S2S1-hardMode-UseBGFalse-AgentPos0505-WoAgentFalse-OcclusionFalse-SkewedFalse-Seed0-Tr50000-Val10000.hdf5'
