defaults:
  - _synthetic_env_base
  - _self_
name: PushN3C4S1S1
dataset_checkpoint:
    entity: ''
    project: ''
    run_id: ''
    file: 'PushEnv-N3-3C4S1S1-hardMode-UseBGFalse-AgentPos0505-WoAgentFalse-OcclusionFalse-SkewedFalse-Seed0-Tr50000-Val10000.hdf5'
