from .gt import GT, GT_Module
from .iodine import Iodine, Iodine_Module
from .monet import MoNet, MoNet_Module
from .naturecnn import NatureCNN, NatureCNN_Module
from .slate import SLATE, SLATE_Module
from .slotattn import SlotAttn, SlotAttn_Module
from .vaes import VAE, VAE_Module
#from .vit import ViT, ViT_Module
from .multiple_cnns import MultipleCNN, MultipleCNN_Module
from .mae import MAE, MAE_Module
