defaults:
  - _base
  - _self_
  - ocr: ???
  - dataset: ???
  - wandb: train_ocr

eval_interval: 1000

hydra:
  run:
    dir: ./outputs/train_ocr/${ocr.name}-${dataset.name}/hydra/${now:%Y-%m-%d_%H-%M-%S}
