defaults:
  - _base
  - _self_
  - ocr: ???
  - pooling: ???
  - dataset: ???
  - wandb: train_classifier

batch_size: 128

classifier:
  d_model: 64
  learning:
      lr: 0.0001

hydra:
  run:
    dir: ./outputs/train_classifier/${ocr.name}-${pooling.name}-${dataset.name}/hydra/${now:%Y-%m-%d_%H-%M-%S}
