name: 'SAC'
algo_kwargs:
    learning_rate: 1e-4
    train_freq: 1
    gradient_steps: 1
    learning_starts: 1000
    buffer_size: 1000000
    gamma: 0.95
    batch_size: 256
    ent_coef: 1e-3
    tau: 0.001
