defaults:
    - _cw_env_base
    - _self_
name: CwFingerImgTargetN4C4S11S1Env
env: CwTargetEnv

mode: 'hard'
target: []
#COLORS: ['blue', 'green', 'yellow', 'red']
COLORS: ['blue', 'green', 'yellow', 'red', 'orange', 'purple', 'brown', 'pink', 'gray', 'olive', 'cyan']

render_mode: 'finger_image'
num_stacked_obss: 3
