defaults:
    - _synthetic_env_base
    - _self_
name: MazeN4C4S4S2Env
env: MazeEnv
num_objects_range: [4,4]
occlusion: True
agent_pos: null
COLORS: ['blue', 'green', 'yellow', 'red']
SHAPES: ['square', 'triangle', 'star_4']
SCALES: [0.15]
