defaults:
    - _synthetic_env_base
    - _self_
env: OddOneOutEnv
name: OddOneOutN4C4S2S2EnvOC
obj_comp: True
COLORS: ['blue', 'green', 'yellow', 'red']
SHAPES: ['square', 'triangle']
SCALES: [0.15, 0.22]
