defaults:
    - _synthetic_env_base
    - _self_
env: OddOneOutEnv
name: OddOneOutN4C3S1S1Env
unseen_combi_mode: "test"
unseen_combi: ['cyan', 'yellow']
COLORS: ['blue', 'cyan', 'yellow']
SHAPES: ['square']
SCALES: [0.15]
