defaults:
    - _synthetic_env_base
    - _self_
env: OddOneOutEnv
name: OddOneOutN4C2S4S2EnvOC
obj_comp: True
COLORS: ['blue', 'green']
SHAPES: ['square', 'triangle', 'star_4', 'circle']
SCALES: [0.15, 0.22]
