defaults:
    - _synthetic_env_base
    - _self_
env: OddOneOutEnv
name: OddOneOutN4C3S1S1Env
unseen_combi_mode: "train"
unseen_combi: ['blue', 'yellow']
COLORS: ['blue', 'green', 'yellow']
SHAPES: ['square']
SCALES: [0.15]
