defaults:
    - _synthetic_env_base
    - _self_
env: OddOneOutEnv
name: OddOneOutN6C2S2S1EnvOC
num_objects_range: [6,6]
obj_comp: True
COLORS: ['blue', 'green']
SHAPES: ['square', 'triangle']
SCALES: [0.15]
