defaults:
    - _synthetic_env_base
    - _self_
env: OddOneOutEnv
name: OddOneOutN4C4S5S2Env
COLORS: ['blue', 'green', 'yellow', 'red']
SHAPES: ['square', 'triangle', 'star_4', 'circle']
SCALES: [0.15, 0.22]
