defaults:
    - _synthetic_env_base
    - _self_
env: OddOneOutEnv
name: OddOneOutN4C4S3S2EnvOC
obj_comp: True
num_objects_range: [4,4]
COLORS: ['blue', 'green', 'yellow', 'red']
SHAPES: ['square', 'triangle', 'star_4']
SCALES: [0.15, 0.22]
