defaults:
    - _synthetic_env_base
    - _self_
name: PushN1C1S1S1Env
env: PushEnv
distance_to_wall: 0.15
agent_pos: null
um_objects_range: [1,1]
target: ['blue', 'square', 0.15]
COLORS: ['blue']
SHAPES: ['square']
SCALES: [0.15]
