defaults:
    - _synthetic_env_base
    - _self_
name: PushN2C3S1S1Env
env: PushEnv
distance_to_wall: 0.15
num_objects_range: [2,2]
target: ['blue', 'square', 0.15]
COLORS: ['blue', 'green', 'pink']
SHAPES: ['square']
SCALES: [0.15]
