defaults:
    - _synthetic_env_base
    - _self_
name: TargetN1C4S3S1Env
env: TargetEnv
num_objects_range: [1,1]
target: ['blue', 'square', 0.15]
COLORS: ['blue', 'green', 'yellow', 'red']
SHAPES: ['square', 'triangle', 'star_4']
SCALES: [0.15]
