defaults:
    - _synthetic_env_base
    - _self_
name: TargetN4C4S3S1Env
env: TargetEnv
target: ['blue', 'square', 0.15]
COLORS: ['blue', 'cyan', 'brown', 'pink']
SHAPES: ['square', 'triangle', 'star_4']
SCALES: [0.15]
